# Project-wide Gradle settings.

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX is enabled by default in AGP
android.useAndroidX=true

# Maintain final resource IDs in app module for Java switch statements
android.nonFinalResIds=false

# Enable Gradle Configuration Cache persistently
org.gradle.configuration-cache=true